In [2]:
import numpy as np

arry1 = np.array([1,2,3])

In [3]:
print(arry1)

[1 2 3]


In [4]:
print(type(arry1))

<class 'numpy.ndarray'>


In [5]:
print(arry1.shape)

(3,)


In [6]:
print(arry1[2])

3


In [7]:
arry1[2]=5

In [8]:
arry1

array([1, 2, 5])

In [9]:
arry2 = np.array([[1,2,3],[3,4,5]])
arry2

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
arry2[1][2]

np.int64(5)

In [12]:
print(arry2.shape)

(2, 3)


In [13]:
arry2[1,2]

np.int64(5)

In [15]:
arry2[1][-2]

np.int64(4)

In [17]:
arrS = np.array(['china','India','Oman','USA'])
arrS

array(['china', 'India', 'Oman', 'USA'], dtype='<U5')

In [18]:
arrR = np.arange(0,20,2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
arrL = np.linspace(0,10, 20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
arr=  np.random.rand(10)
arr

array([0.51501326, 0.60066254, 0.1910077 , 0.42858708, 0.78397645,
       0.55992714, 0.90607068, 0.46325539, 0.57115713, 0.20162589])

In [21]:
arr=  np.random.rand(3,4)
arr

array([[0.65731333, 0.41009871, 0.23532543, 0.3079634 ],
       [0.83489076, 0.57733368, 0.74852271, 0.77149681],
       [0.8332313 , 0.71296975, 0.98947937, 0.47856263]])

In [22]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
arr = [0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [31]:
print(np.tile(arr,3)) 

[0 1 2 0 1 2 0 1 2]


In [34]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [36]:
arr = np.random.rand(5,5)
arr 

array([[0.51467363, 0.41024099, 0.22273631, 0.50638091, 0.89153916],
       [0.89461074, 0.08707751, 0.02443799, 0.67033512, 0.17146541],
       [0.9179927 , 0.57074444, 0.11628401, 0.52267768, 0.20700604],
       [0.36097883, 0.20514646, 0.59947198, 0.13111985, 0.1538095 ],
       [0.41834404, 0.00952192, 0.49952419, 0.99956215, 0.44834211]])

In [37]:
np.diag(arr)

array([0.51467363, 0.08707751, 0.11628401, 0.13111985, 0.44834211])

In [38]:
arr.ndim

2

In [39]:
arr.size

25

In [40]:
arr.shape

(5, 5)

In [41]:
np.random.randint(-10,10,4)

array([ 7, -9, -7,  0], dtype=int32)

In [46]:
arr/2

array([[0.25733681, 0.2051205 , 0.11136815, 0.25319046, 0.44576958],
       [0.44730537, 0.04353875, 0.01221899, 0.33516756, 0.08573271],
       [0.45899635, 0.28537222, 0.05814201, 0.26133884, 0.10350302],
       [0.18048941, 0.10257323, 0.29973599, 0.06555993, 0.07690475],
       [0.20917202, 0.00476096, 0.2497621 , 0.49978108, 0.22417105]])

In [47]:
np.exp(arr)

array([[1.67309237, 1.50718096, 1.24949105, 1.65927526, 2.43888059],
       [2.44638333, 1.09098124, 1.02473904, 1.95489234, 1.18704308],
       [2.50425855, 1.7695839 , 1.12331486, 1.68653762, 1.22999   ],
       [1.43473308, 1.22770486, 1.82115693, 1.14010442, 1.16626869],
       [1.51944334, 1.0095674 , 1.64793699, 2.7170919 , 1.56571425]])

In [48]:
arr

array([[0.51467363, 0.41024099, 0.22273631, 0.50638091, 0.89153916],
       [0.89461074, 0.08707751, 0.02443799, 0.67033512, 0.17146541],
       [0.9179927 , 0.57074444, 0.11628401, 0.52267768, 0.20700604],
       [0.36097883, 0.20514646, 0.59947198, 0.13111985, 0.1538095 ],
       [0.41834404, 0.00952192, 0.49952419, 0.99956215, 0.44834211]])

In [55]:
np.tan(arr)

array([[0.56551077, 0.43491775, 0.22649432, 0.55461686, 1.23849206],
       [1.24630477, 0.08729827, 0.02444285, 0.79279979, 0.17316579],
       [1.30780887, 0.64201933, 0.11681099, 0.5761228 , 0.21001445],
       [0.37752077, 0.20807361, 0.68336193, 0.13187648, 0.155034  ],
       [0.44458781, 0.00952221, 0.54568484, 1.55590889, 0.48101195]])

In [56]:
arr

array([[0.51467363, 0.41024099, 0.22273631, 0.50638091, 0.89153916],
       [0.89461074, 0.08707751, 0.02443799, 0.67033512, 0.17146541],
       [0.9179927 , 0.57074444, 0.11628401, 0.52267768, 0.20700604],
       [0.36097883, 0.20514646, 0.59947198, 0.13111985, 0.1538095 ],
       [0.41834404, 0.00952192, 0.49952419, 0.99956215, 0.44834211]])

In [69]:
np.var(arr)

np.float64(0.0824486891078064)

In [71]:
arr[1:, 2: -1]

array([[0.02443799, 0.67033512],
       [0.11628401, 0.52267768],
       [0.59947198, 0.13111985],
       [0.49952419, 0.99956215]])

In [74]:
np.sort(arr)

array([[0.22273631, 0.41024099, 0.50638091, 0.51467363, 0.89153916],
       [0.02443799, 0.08707751, 0.17146541, 0.67033512, 0.89461074],
       [0.11628401, 0.20700604, 0.52267768, 0.57074444, 0.9179927 ],
       [0.13111985, 0.1538095 , 0.20514646, 0.36097883, 0.59947198],
       [0.00952192, 0.41834404, 0.44834211, 0.49952419, 0.99956215]])

In [76]:
arr[:3, :]

array([[0.51467363, 0.41024099, 0.22273631, 0.50638091, 0.89153916],
       [0.89461074, 0.08707751, 0.02443799, 0.67033512, 0.17146541],
       [0.9179927 , 0.57074444, 0.11628401, 0.52267768, 0.20700604]])

In [81]:
arr[:3, :].flatten()

array([0.51467363, 0.41024099, 0.22273631, 0.50638091, 0.89153916,
       0.89461074, 0.08707751, 0.02443799, 0.67033512, 0.17146541,
       0.9179927 , 0.57074444, 0.11628401, 0.52267768, 0.20700604])

In [83]:
arr = np.array ([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [87]:
arr1 = np.append(arr,9)
arr1

array([4, 5, 6, 7, 8, 9])

In [93]:
arr2 = np.insert(arr,0,[1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
arr3 = np.delete(arr2, [1,3])
arr3

array([1, 3, 5, 6, 7, 8])

In [98]:
arrC =arr3.copy()
arrC

array([1, 3, 5, 6, 7, 8])

In [110]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr_cat=np.concatenate((arr1,arr2), axis=1)
print(arr_cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [112]:
cat = np.hstack((arr1,arr2))
cat

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [113]:
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [114]:
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 2 1 2]


In [119]:
# intersection,differentiate, neither 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1,arr2))
print(np.union1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))
print(np.setxor1d(arr1,arr2))

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]
